name: flutter_getx_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  flutter_dotenv: 5.0.2
  flutter_staggered_grid_view: 0.6.1
  fluttertoast: 8.0.9
  get_storage: 2.0.3
  http: 0.13.4
  intl: 0.17.0
  json_annotation: 4.5.0
  logger: 1.1.0
  pull_to_refresh: 2.0.0
  retrofit: 3.0.1+1
  rxdart: 0.27.4
  cached_network_image: 3.2.1
  change_app_package_name: 1.1.0
  http_interceptor: 1.0.2
  firebase_messaging: 11.4.2
  build: 2.3.0
  firebase_core: 1.18.0
  flutter_local_notifications: 9.6.1
  flutter_svg: 0.23.0+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  build_runner: 2.1.11
  retrofit_generator: 4.0.1
  json_serializable: 6.2.0
  flutter_launcher_icons: 0.9.3
  flutter_flavorizr: 2.1.3
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/logos/logo.png
  ios: true

flavorizr: 
  app: 
    android: 
      flavorDimensions: flavor-type
    ios: null
  flavors: 
    dev: 
      app: 
        name: GetxTemplateDev
      android: 
        applicationId: com.example.flutter_getx_template.dev
      ios: 
        bundleId: com.example.flutter_getx_template.dev
    production: 
      app: 
        name: GetxTemplate
      android: 
        applicationId: com.example.flutter_getx_template
      ios: 
        bundleId: com.example.flutter_getx_template

flutter: 
  assets: 
    - assets/logos/
    - assets/images/
  uses-material-design: true

